name: Build and Publish Artifacts

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the main repository
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Checkout the secondary repository (update the repository value)
      - name: Checkout Secondary Repository
        uses: actions/checkout@v3
        with:
          repository: STEMgraph/document-generator
          path: document_generator

      # 3. Setup Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 4. Run the Python scripts that generate the output files
      - name: Run Python Scripts
        run: |
          # Adjust the paths as needed.
          python3 document_generator/python3 parse_to_html.py challenge.stemgraph challenge.html
          python3 document_generator/python3 parse_to_md.py challenge.stemgraph challenge.md
          python3 document_generator/python3 parse_to_latex.py challenge.stemgraph challenge.tex
          
      # 5. Rename challenge.md to README.md and commit the change
      - name: Update README.md from challenge.md
        run: |
          if [ -f challenge.md ]; then
            mv challenge.md README.md
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README.md from challenge.md" || echo "No changes to commit."
            git push
          else
            echo "challenge.md not found!"
          fi

      # 6. Install LuaLaTeX and compile challenge.tex
      - name: Install LuaLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-luatex

      - name: Compile challenge.tex with LuaLaTeX and Commit PDF
        run: |
          if [ -f challenge.tex ]; then
            lualatex challenge.tex
            # Assuming lualatex produces challenge.pdf as output.
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add challenge.pdf
            git commit -m "Update PDF compiled from challenge.tex" || echo "No changes to commit."
            git push
          else
            echo "challenge.tex not found!"
          fi

      # 7. Rename challenge.html to index.html and update the gh-pages branch
      - name: Update gh-pages with index.html from challenge.html
        run: |
          if [ -f challenge.html ]; then
            mv challenge.html index.html
            # Fetch the gh-pages branch if it exists
            git fetch origin gh-pages
            # Checkout gh-pages branch; if it does not exist, create an orphan branch
            git checkout gh-pages || git checkout --orphan gh-pages
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add index.html
            git commit -m "Update gh-pages index.html from challenge.html" || echo "No changes to commit."
            git push origin gh-pages
          else
            echo "challenge.html not found!"
          fi
