name: Build and Release STEMgraph Challenge

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  call-build-release:
    uses: STEMgraph/release_workflow/.github/workflows/release_stemgraph_challenge.yml@v0.0.1
    secrets: inherit
